index:
    path: /
    controller: App\Controller\ViewController::index
register:
  path: /Register
  controller: App\Controller\AuthController::register
login:
  path: /Login
  controller: App\Controller\AuthController::login
logout:
  path: /Logout
  controller: App\Controller\AuthController::logout
addList:
  path: /List/Add
  controller: App\Controller\ListController::addList
allLists:
  path: /List
  controller: App\Controller\ListController:allLists
list:
  path: /List/Detail/{id}
  controller: App\Controller\ListController:detailedList
entryAdd:
  path: /List/Detail/{id}/Add
  controller: App\Controller\ListController:addEntry
admin:
  path: /Admin
  controller: App\Controller\AdminController:view
admin_userlist:
  path: /Admin/Users
  controller: App\Controller\AdminController:users
admin_lists:
  path: /Admin/Lists
  controller: App\Controller\AdminController:lists
userpanel:
  path: /User/{name}/Panel
  controller: App\Controller\UserController:view
user:
  path: /User/{name}
  controller: App\Controller\UserController:user